CREATE OR REPLACE PROCEDURE greetings
AS
BEGIN
	DBMS_OUTPUT.PUT_LINE('PROCEDURE EXECUTED');
END;
/

CREATE OR REPLACE FUNCTION totalCustomers
RETURN NUMBER IS
total number(2):=0;
BEGIN
	SELECT COUNT(*) INTO total
	FROM customers;

	RETURN total;
	
END;
/